"""The localized top navigation.

The navigation is regenerated by the renderer rather than translated as
content, so that option `value` attributes — the things that actually make the
site navigable — are carried over untouched by construction.
"""
import html as ihtml
import re

from .document import splice
from .markup import set_attr

BUTTON_LABELS = {"Home": "首页", "Prev": "上一页", "Next": "下一页"}
SITE_PREFIX = {"en": "../../chapters/", "zh": "../../zh/chapters/",
               "bilingual": "../../bilingual/chapters/"}
SWITCH_LABELS = {"en": "EN", "zh": "中", "bilingual": "对照"}


def localize_header(doc, header, nav, mode, page_file):
    """Rewrite one page's top navigation for the zh or bilingual site."""
    replacements = []
    for el in header.descendants():
        if el.tag == "optgroup":
            label = el.attrs.get("label", "")
            localized = _label(label, nav, mode)
            if localized != label:
                replacements.append((el.start, el.content_start,
                                     set_attr(doc.open_tag(el), "label",
                                              ihtml.escape(localized))))
        elif el.tag == "option":
            replacements.append(_inner_swap(doc, el,
                                            _label(doc.inner(el), nav, mode)))
        elif "book-title" in el.classes:
            replacements.append(_inner_swap(doc, el,
                                            _label(doc.inner(el), nav, "zh")))
        elif "navbtn" in el.classes:
            replacements.append(_inner_swap(doc, el, _button(doc.inner(el))))

    buttons = next((el for el in header.descendants()
                    if "nav-buttons" in el.classes), None)
    if buttons is not None and page_file:
        replacements.append((buttons.end, buttons.end,
                             language_switch(mode, page_file)))

    replacements = [r for r in replacements if r is not None]
    return splice(doc.src, header.start, header.end, replacements)


def nav_labels(doc, header):
    """Every English string the localized navigation needs a translation for.

    The keys are exactly what `_label` will look up, so a skeleton built from
    this list can never miss by a stray entity or a space.
    """
    labels = []
    for el in header.descendants():
        if el.tag == "optgroup":
            text = el.attrs.get("label", "")
        elif el.tag == "option" or "book-title" in el.classes:
            text = doc.inner(el)
        else:
            continue
        text = ihtml.unescape(text)
        if text.strip():
            labels.append(text)
    return labels


def language_switch(mode, page_file):
    """EN / 中 / 对照, always pointing at the same chapter."""
    parts = []
    for site in ("en", "zh", "bilingual"):
        label = SWITCH_LABELS[site]
        if site == mode:
            parts.append('<span class="langbtn active">%s</span>' % label)
        else:
            parts.append('<a class="langbtn" href="%s%s">%s</a>'
                         % (SITE_PREFIX[site], page_file, label))
    return '\n    <div class="langswitch">%s</div>' % "".join(parts)


def _inner_swap(doc, el, text):
    current = doc.inner(el)
    if text == current:
        return None
    return (el.content_start, el.content_end, text)


def _label(text, nav, mode):
    english = ihtml.unescape(text)
    chinese = nav.get(english)
    if not chinese:
        return text
    if mode == "bilingual":
        return "%s / %s" % (ihtml.escape(english), ihtml.escape(chinese))
    return ihtml.escape(chinese)


def _button(text):
    for english, chinese in BUTTON_LABELS.items():
        text = re.sub(r"\b%s\b" % english, chinese, text)
    return text
